
jwt:
  header: Authorization
  expire: 604800 # 7天，s为单位
  secret: HRlELXqpSB

# 服务端口
server:
  port: 8088

# 数据源配置
spring:

  # 邮箱基本配置
  mail:
    # 配置 smtp 服务主机地址
    # qq 邮箱     smtp.qq.com    端口号 465 或 587
    # sina       smtp.sina.com
    # aliyun     smtp.aliyun.com
    # 163        smtp.163.com   端口号 465 或 994
    host: smtp.qq.com
    # 发送者邮箱
    username: 2529095199@qq.com
    # 在邮箱内申请的授权码
    password: atniiybnjelkecai
    # 端口号
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 其他参数
    properties:
      mail:
        # 配置SSL 加密工厂
        smtp:
          ssl:
            # 本地测试， 先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

  # Redis基础配置
  redis:
    database: 0 # 0也是默认值，表示你要操控的 Redis 上的哪个数据库
    port: 6379  # 6379也是默认值，表示 Redis 端口
    host: 203.195.195.64     # 这里填写你的服务器地址
    password: 123456

  # 解决swagger3空指针报错
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  # 数据库配置
  datasource:
    name: demo
    url: jdbc:mysql://203.195.195.64:3306/demo?&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    ## 配置连接池信息
    ## 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 30
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    # 超过时间限制是否回收
    removeAbandoned: true
    # 超时时间；单位为秒。180秒=3分钟
    removeAbandonedTimeout: 180
    # 关闭abanded连接时输出错误日志
    logAbandoned: true

# mybatis-plus 默认扫描mapper.xml的目录
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #配置sql打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


